from pathlib import Path

from pcse.crop.lintul_cassava10 import LINTUL_CASSAVA_NO_NUTRIENT_STRESS
from pcse.soil.lintul_cassava_soil_wrappers import Lintul_Cassava_WLP_SoilWrapper
from pcse.agromanager import AgroManager

SOIL = Lintul_Cassava_WLP_SoilWrapper
CROP = LINTUL_CASSAVA_NO_NUTRIENT_STRESS
AGROMANAGEMENT = AgroManager
OUTPUT_VARS = ["SM", "W", "RROOTD", "ROOTD", "LAI", "WLVG", "WST", "WSO", "ANLVG", "ANST", "ANSO", "APLVG", "APST", "APSO", "AKLVG", "AKST", "AKSO", "RFTRA",'NAVAIL', 'PAVAIL', 'KAVAIL', "NNI", "PNI", "KNI", "KNI", "NPKI"]
OUTPUT_INTERVAL = "daily"
OUTPUT_INTERVAL_DAYS = 1
OUTPUT_WEEKDAY = 0
SUMMARY_OUTPUT_VARS = []
TERMINAL_OUTPUT_VARS = []